name: mda-tests
channels:
  - biobuilds
  - conda-forge
dependencies:
  - pip
  - mmtf-python
  - biopython
  - networkx
  - cython
  - matplotlib
  - scipy
  - griddataformats
  - hypothesis
  - gsd
  - seaborn>=0.7.0
  - clustalw=2.1
  - netcdf4
  - scikit-learn
  - joblib>=0.12
  - chemfiles
  - tqdm>=4.43.0
  - tidynamics>=1.0.0
  - rdkit>=2020.03.1
  - h5py==2.10.0
  - pip:
    - duecredit
    - parmed
