name: macOS_CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test_full:
    if: "github.repository == 'IAlibay/mdanalysis'"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        max-parallel: 9
        matrix:
          os: [macOS-latest, ubuntu-latest, windows-latest]
          python-version: [3.6, 3.7, 3.8]
    env:
      PYTEST_FLAGS: "--disable-pytest-warnings --durations=50"
      PYTEST_LIST: "testsuite/MDAnalysisTests"
      MAIN_CMD: "pytest -n2 ${PYTEST_LIST}"
      SETUP_CMD: "${PYTEST_FLAGS}"
      BUILD_CMD: "pip install -e package/ && (cd testsuite/ && python setup.py build)"
      CYTHON_TRACE_NOGIL: 1
      MPLBACKEND: agg
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
    - uses: actions/checkout@v2
    - name: setup_miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        channel-priority: flexible
        add-pip-as-python-dependency: true
        mamba-version: "*"
        architecture: x64
        environment-file: maintainer/test-envs/conda-full.yaml
        activate-environment: mda-tests
    
    - name: setup_and_check
      run: |
        # macos things
        echo "checking os:"
        echo ${{ matrix.os }}
        # Check python
        which python
        which pip
        conda info
        conda list

    - name: install_hole
      run:
        # bash ./maintainer/install_hole.sh ${OS_NAME} "${HOME}"
        # HOLE_BINDIR=${HOME}/hole2/exe
        # export PATH=${PATH}:${HOLE_BINDIR}

    - name: install_mda
      run: |
        eval $BUILD_CMD

    - name: run_tests
      run: |
        ulimit -S -n 2048
        pip install pytest
        echo $MAIN_CMD $SETUP_CMD
        eval $MAIN_CMD $SETUP_CMD

    - name: the_end
      run: |
        echo "All in a day's work"
