name: macOS_CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test_macos:
    if: "github.repository == 'IAlibay/mdanalysis'"
    runs-on: macos-latest
    strategy:
        max-parallel: 3
        matrix:
          python-version: [3.6, 3.7, 3.8]
    env:
      GH_DOC_BRANCH: develop
      GH_REPOSITORY: github.com/MDAnalysis/mdanalysis.git
      BUILD_DOCS: false
      CODECOV: false
      PYTEST_FLAGS: "--disable-pytest-warnings --durations=50"
      PYTEST_LIST: "testsuite/MDAnalysisTests"
      MAIN_CMD: "pytest ${PYTEST_LIST}"
      SETUP_CMD: "${PYTEST_FLAGS}"
      BUILD_CMD: "pip install -e package/ && (cd testsuite/ && python setup.py build)"
      CONDA_MIN_DEPENDENCIES: "mmtf-python biopython networkx cython matplotlib scipy griddataformats hypothesis gsd codecov"
      CONDA_DEPENDENCIES: "${CONDA_MIN_DEPENDENCIES} seaborn>=0.7.0 clustalw=2.1 netcdf4 scikit-learn joblib>=0.12 chemfiles tqdm>=4.43.0 tidynamics>=1.0.0 rdkit>=2020.03.1 h5py==2.10.0"
      CONDA_CHANNEL_PRIORITY: True
      PIP_DEPENDENCIES: "duecredit parmed"
      NUMPY_VERSION: 1.17.3
      INSTALL_HOLE: "true"
      CYTHON_TRACE_NOGIL: 1
      MPLBACKEND: agg
      MAMBA: true

    steps:
    - uses: actions/checkout@v2
    - name: setup_miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        channel-priority: flexible
        channels: biobuilds, conda-forge
        mamba-version: "*"
        architecture: x64
    
    - name: install_dependencies
      run: |
        # Check conda
        conda info
        conda list
        conda config --show-sources
        conda config --show
        
        # Check env variables
        echo $NUMPY_VERSION
        export MACOSX_DEPLOYMENT_TARGET=10.9
        conda install --y $CONDA_DEPENDENCIES

    - name: setup
      run: |
        ulimit -S -n 2048
        pip install pytest
        echo $MAIN_CMD $SETUP_CMD
        eval $MAIN_CMD $SETUP_CMD

    - name: the_end
      run: |
        echo "All in a day's work"
