name: macOS_CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test_macos:
    if: "github.repository == 'IAlibay/mdanalysis'"
    runs-on: macos-latest
    strategy:
        max-parallel: 3
        matrix:
          python-version: [3.6, 3.7, 3.8]
    env:
      GH_DOC_BRANCH: develop
      GH_REPOSITORY: github.com/MDAnalysis/mdanalysis.git
      BUILD_DOCS: false
      CODECOV: false
      PYTEST_FLAGS: "--disable-pytest-warnings --durations=50"
      PYTEST_LIST: "testsuite/MDAnalysisTests"
      MAIN_CMD: "pytest ${PYTEST_LIST}"
      SETUP_CMD: "${PYTEST_FLAGS}"
      BUILD_CMD: "pip install -e package/ && (cd testsuite/ && python setup.py build)"
      CYTHON_TRACE_NOGIL: 1
      MPLBACKEND: agg
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
    - uses: actions/checkout@v2
    - name: setup_miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        channel-priority: flexible
        add-pip-as-python-dependency: true
        channels: biobuilds, conda-forge
        mamba-version: "*"
        architecture: x64
        environment-file: maintainer/test-envs/conda-full.yaml
        activate-environment: mda-tests
    
    - name: check_dependencies
      run: |
        # Check conda
        which python
        which pip
        conda info
        conda list

    - name: setup
      run: |
        ulimit -S -n 2048
        pip install pytest
        echo $MAIN_CMD $SETUP_CMD
        eval $MAIN_CMD $SETUP_CMD

    - name: the_end
      run: |
        echo "All in a day's work"
